autocomplete/urls.py
from django.urls import path

from . import views


app_name = "autocomplete"

urlpatterns = [path("", views.complete, name="complete")]

food_choice/urls.py
"""Centralize the application urls"""

from django.urls import path

from . import views


app_name = "food_choice"

urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "legal_notices/",
        views.legal_notices,
        name="legal_notices",
    ),
    path(
        "product/<int:product_id>/",
        views.product,
        name="product",
    ),
    path(
        "products/",
        views.products,
        name="products",
    ),
    path(
        "substitutes/<int:product_id>/",
        views.substitutes,
        name="substitutes",
    ),
    path(
        "save_as_favoris/<int:product_id>/<int:substitute_id>/",
        views.save_as_favoris,
        name="save_as_favoris",
    ),
    path(
        "delete_favoris/<int:favorite_id>/",
        views.delete_favoris,
        name="delete_favoris",
    ),
    path(
        "favorites/",
        views.favorites,
        name="favorites",
    ),
]

pur_beurre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path

from users import views as user_views


urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("food_choice.urls", namespace="food_choice"),
    ),
    path(
        "autocomplete/",
        include(
            "autocomplete.urls",
            namespace="autocomplete",
        ),
    ),
    path(
        "register/",
        user_views.register,
        name="register",
    ),
    path(
        "profile/",
        user_views.profile,
        name="profile",
    ),
    path(
        "profile/update/",
        user_views.update_profile,
        name="update_profile",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password_reset",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/complete",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'src/assets/img/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
        rel="stylesheet" type="text/css" />
    <!-- Third party plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
        rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'dist/css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'style.css' %}" rel="stylesheet" />
    <link href="{% static 'css/autocomplete.css' %}" rel="stylesheet" />
    <title>Pur Beurre - Pour le bon gras!</title>
</head>

<body id="page-top">

    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container">

            <a class="navbar-brand js-scroll-trigger" href="/"><img src="{% static '/src/assets/img/logo.png' %}"
                    alt="logo"> Pur Beurre</a>
            <button class="navbar-toggler navbar-toggler-right justify-content-center" type="button"
                data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">
                    <li class="nav-item"></li>
                    <form method="POST" action="{% url 'food_choice:products' %}">
                        {% csrf_token %}
                        {{ nav_form }}
                    </form>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'profile' %}"><img
                                src="{% static '/src/assets/img/account_online.png' %}" title="Profile"
                                alt="Profile"></a>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger"
                            href="{% url 'food_choice:favorites' %}"><img
                                src="{% static '/src/assets/img/logo_carrot.png' %}" title="Favoris" alt="Favoris"></a>
                    </li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'logout' %}"><img
                                src="{% static '/src/assets/img/account_logout.png' %}" title="Déconnexion"
                                alt="Déconnexion"></a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'register' %}"><img
                                src="{% static '/src/assets/img/account.png' %}" title="Créer un compte"
                                alt="Créer un compte"></a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'login' %}"><img
                                src="{% static '/src/assets/img/account_online.png' %}" title="Connexion"
                                alt="Connexion"></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="small text-center text-muted"><a href="{% url 'food_choice:legal_notices' %}">Mentions
                            légales</a></div>
                </div>
                <div class="col-lg-6">
                    <div class="small text-center text-muted"><a href="mailto:contact@purbeurre.com">Contact</a></div>
                </div>
            </div>
        </div>
    </footer>


    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'dist/js/scripts.js' %}"></script>



    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
        integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <script>
        const autocomplete_url = "{% url 'autocomplete:complete' %}";
    </script>
    <script src="{% static 'js/autocomplete.js' %}"></script>

</body>

</html>