food_choice/urls.py
"""Centralize the application urls"""

from django.urls import path

from . import views


app_name = "food_choice"

urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "legal_notices/",
        views.legal_notices,
        name="legal_notices",
    ),
    path(
        "product/<int:product_id>/",
        views.product,
        name="product",
    ),
    path(
        "products/",
        views.products,
        name="products",
    ),
    path(
        "substitutes/<int:product_id>/",
        views.substitutes,
        name="substitutes",
    ),
    path(
        "save_as_favoris/<int:product_id>/<int:substitute_id>/",
        views.save_as_favoris,
        name="save_as_favoris",
    ),
    path(
        "delete_favoris/<int:favorite_id>/",
        views.delete_favoris,
        name="delete_favoris",
    ),
    path(
        "favorites/",
        views.favorites,
        name="favorites",
    ),
]

pur_beurre/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path

from users import views as user_views


urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("food_choice.urls", namespace="food_choice"),
    ),
    path(
        "autocomplete/",
        include(
            "autocomplete.urls",
            namespace="autocomplete",
        ),
    ),
    path(
        "register/",
        user_views.register,
        name="register",
    ),
    path(
        "profile/",
        user_views.profile,
        name="profile",
    ),
    path(
        "profile/update/",
        user_views.update_profile,
        name="update_profile",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password_reset",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/complete",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

food_choice/models.py
"""Models used by the application."""

from django.db import models
from django.utils import timezone

from food_choice.managers import ProductManager
from users.models import User


class Category(models.Model):
    """Represente the categories of a product"""

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    """Represente a product"""

    name = models.CharField(max_length=150, null=True)
    code = models.CharField(max_length=13, unique=True)
    brand = models.CharField(max_length=100, null=True)
    photo_url = models.TextField(null=True)
    product_url = models.TextField(null=True)
    nutrition_grade = models.CharField(max_length=1)
    energy_100g = models.IntegerField(default=0)
    fat = models.IntegerField(default=0)
    saturates = models.IntegerField(default=0)
    carbohydrate = models.IntegerField(default=0)
    sugars = models.IntegerField(default=0)
    protein = models.IntegerField(default=0)
    fiber = models.IntegerField(default=0)
    salt = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category, related_name="product")

    objects = ProductManager()

    def __str__(self):
        return f"{self.name}, {self.code}, {self.nutrition_grade}"


class Favoris(models.Model):
    """Represente the user's favorites products"""

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="favorite_product"
    )
    substitute = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="favorite_substitute"
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="favorite_owner"
    )
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["product", "substitute", "owner"],
                name="unique_user_favoris",
            )
        ]

    def __str__(self):
        return f"{self.owner}: {self.substitute} substitute {self.product}"

food_choice/forms.py
"""Create the forms of the application."""

from django import forms


class NavResearchForm(forms.Form):
    user_research = forms.CharField(
        max_length=50,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Votre aliment",
                "type": "text",
                "name": "nav_search",
                "id": "nav_search",
                "class": "rounded autocomplete_search",
                "size": "25",
            }
        ),
    )


class HomeResearchForm(forms.Form):
    user_research = forms.CharField(
        max_length=50,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Votre aliment",
                "type": "text",
                "name": "home_search",
                "id": "home_search",
                "class": "rounded autocomplete_search",
                "size": "30",
                "autofocus": "autofocus",
            }
        ),
    )

food_choice/views.py
"""Views used by the application."""

import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Count
from django.shortcuts import redirect
from django.shortcuts import render

from users.models import User

from .forms import HomeResearchForm
from .models import Category
from .models import Favoris
from .models import Product


# Get an instance of a logger
logger = logging.getLogger(__name__)


def home(request):
    """Display the home page of the application"""

    context = {
        "home_form": HomeResearchForm(),
    }

    return render(
        request,
        "food_choice/home.html",
        context,
    )


def legal_notices(request):
    """Display the legal notices page of the application"""

    return render(
        request,
        "food_choice/legal_notices.html",
    )


def product(request, product_id):
    """Display a list of products according to the user research"""
    product = Product.objects.get(pk=product_id)

    context = {
        "product": product,
    }

    return render(request, "food_choice/product.html", context)


def products(request):
    """Display a list of products according to the user research"""
    if request.method == "POST":
        user_research = request.POST["user_research"]

        products = Product.objects.filter(
            name__icontains=user_research.lower(),
        )

        context = {
            "title": user_research,
            "sentence": "Vous recherchez peut-être...",
            "products": products,
        }

        logger.info(
            "New search",
            exc_info=True,
            extra={
                "request": user_research,
            },
        )

        return render(request, "food_choice/products.html", context)


def substitutes(request, product_id):
    """Display the detailed sheet of the selected product"""
    product = Product.objects.get(pk=product_id)  # find the product in BD

    categories = Category.objects.filter(
        product__name=product.name
    ).distinct()  # find its categories

    # find similare products wich share at least 4 categories,
    # with the same or a better nutrition grade
    # and order by grade
    substitutes = (
        Product.objects.filter(categories__in=categories)
        .annotate(nb_cat=Count("categories"))
        .filter(nb_cat__gte=4)
        .filter(nutrition_grade__lt=product.nutrition_grade)
        .exclude(nutrition_grade="")
        .order_by("nutrition_grade")
    )

    favoris = []
    current_user = request.user
    if current_user != "AnonymousUser":
        favoris_obj = Favoris.objects.filter(owner_id=current_user.id)
        for one_favoris in favoris_obj:
            favoris.append(one_favoris.substitute.id)

    context = {
        "title": product.name,
        "product_url": product.photo_url,
        "searched_product": product_id,
        "sentence": "Vous pouvez substituer votre recherche par...",
        "substitutes": substitutes,
        "favoris": favoris,
    }

    return render(request, "food_choice/substitutes.html", context)


@login_required
def save_as_favoris(request, product_id, substitute_id):
    """save as the user's favorite product, if he's logged in"""
    product = Product.objects.get(pk=product_id)
    substitute = Product.objects.get(pk=substitute_id)
    user = User.objects.get(pk=request.user.id)
    # insert product, substitute and user
    favoris = Favoris(product=product, substitute=substitute, owner=user)

    try:
        favoris.save()
        messages.success(
            request,
            f"{substitute.name} a bien été ajouté à vos favoris"
        )
        return redirect("food_choice:favorites")
    except IntegrityError:
        messages.error(
            request,
            f"Erreur: {substitute.name} n'a pas pu être enregistré",
        )
        return redirect("food_choice:home")


@login_required
def delete_favoris(request, favorite_id):
    """delete a favorite product user, if he's logged in"""
    favoris = Favoris.objects.get(pk=favorite_id)

    try:
        favoris.delete()
        messages.success(
            request,
            f"{substitute.name} a bien été retiré de vos favoris"
        )
        return redirect("food_choice:favorites")
    except IntegrityError:
        messages.error(
            request,
            f"Erreur: {favoris.name} n'a pas pu être supprimé",
        )
        return redirect("food_choice:home")


@login_required
def favorites(request):
    """display the user's favorite products, if he's logged in"""
    favorites = Favoris.objects.filter(owner_id=request.user.id)

    context = {
        "title": "Mes produits favoris",
        "research": "favorites",
        "favorites": favorites,
    }

    return render(request, "food_choice/favorites.html", context)

food_choice/templates/food_choice/favorites.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white">{{ title }}</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
            </div>
        </div>
    </div>
</header>

<div class="jumbotron">
    <h2 class="text-center">{{ sentence }}</h2>
</div>

<section>
    <div class="container">
        <div class="row">
            {% for favorite in favorites %}
            {% if favorite.substitute.nutrition_grade and favorite.substitute.photo_url %}
            <div class="col-lg-4 col-md-12">

                <a href="{% url 'food_choice:product' favorite.substitute.id %}" title="Fiche produit" target="_blank">
                    <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
                        <img class="card-img-top" src="{{ favorite.substitute.photo_url }}" alt="Image du produit">

                        <span
                            class="nutriscore-{{favorite.substitute.nutrition_grade}}">{{favorite.substitute.nutrition_grade}}</span>

                        <div class="card-body text-center">
                            {% if favorite.substitute.name %}
                            <h6 class="card-title">{{ favorite.substitute.name }}</h6>
                            {% else %}
                            <h6 class="card-title">Nom: non renseigné</h6>
                            {% endif %}
                            <a class="btn btn-primary js-scroll-trigger"
                                href="{% url 'food_choice:delete_favoris' favorite.id %}">
                                <img src="{% static 'src/assets/img/delete.png' %}" alt="Supprimer">
                                Supprimer</a>
                        </div>
                        <div class="card-footer font-italic text-muted"><a
                                href="{% url 'food_choice:product' favorite.product.id %}" target="_blank">
                                Substitut de : {{ favorite.product.name }}</a>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

food_choice/templates/food_choice/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white">Du gras, oui, mais de qualité !</h1>
                <hr class="divider my-4" />
                <h2 class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que
                    vous consommez tous les jours</h2>

            </div>
            <div class="col-lg-8 align-self-baseline">
                <form action="{% url 'food_choice:products' %}" method="POST">
                    {% csrf_token %}
                    {{ home_form }}
                    <input id="center-home-btn" class="btn btn-primary js-scroll-trigger" type="submit"
                        value="Chercher" />
                </form>
            </div>
        </div>
    </div>
</header>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}

<!-- Services-->
<section class="page-section" id="services">
    <div class="container">
        <h2 class="text-center mt-0">Colette et Remy</h2>
        <hr class="divider my-4" />
        <p class="text-center mt-0">Remy et Colette sont amoureux de la gastronomie française. Ils Travaillent
            quotidiennement avec les meilleurs produits du terroir, ils affectionnent particulièrement la bonne chaire
            et aiment partager leur passion.</p>
        <div class="row">
            <div class="col-lg-6 col-md-12 text-center">
                <div class="mt-5">
                    <img src="{% static 'src/assets/img/colette.png' %}" alt="Colette"
                        class="border border-white max-width: 100% height: auto" />
                    <!-- <i class="fas fa-4x fa-gem text-primary mb-4"></i> -->
                    <h3 class="h4 mb-2">Colette</h3>
                    <div>
                        <p class=text-justify>"Nous aimons tous manger, surtout en France ! Personnellement, une
                            baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme
                            tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue
                            compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les
                            produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et
                            souvent pour le même prix !" </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-12 text-center">
                <div class="mt-5">
                    <img src="{% static 'src/assets/img/remy.png' %}" alt="Remy"
                        class="border border-white max-width: 100% height: auto" />
                    <!-- <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i> -->
                    <h3 class="h4 mb-2">Rémy</h3>
                    <div>
                        <p class=text-justify>"Pour ma part je me rendais déjà dans bien des magasins car j'aime
                            beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le
                            contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments
                            vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un
                            aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Contact-->
<section class="page-section" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="mt-0">Contactez-nous !</h2>
                <hr class="divider my-4" />
                <p class="text-muted mb-5">Une question, une suggestion, un avis...</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                <div>+33 (0)6 05 04 03 02</div>
            </div>
            <div class="col-lg-4 mr-auto text-center">
                <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                <a class="d-block" href="mailto:contact@purbeurre.com">contact@purbeurre.com</a>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

food_choice/templates/food_choice/legal_notices.html
{% extends 'base.html' %}
{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white">Mentions légales</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
            </div>
        </div>
    </div>
</header>

<section class="page-section">
    <div class="container">
        <div class="content-section">
            <legend class="border-bottom mb-4">Projet réalisé dans le cadre du parcours Développeur Python <a
                    href="https://openclassrooms.com/fr/paths/322-developpeur-dapplication-python"
                    target="_blank">OpenClassrooms.</a></legend>
            <ul>
                <li>Données/API: <a href="https://world.openfoodfacts.org/data" target="_blank">OpenFoodFacts</a></li>
                <li>Déployement: <a href="https://www.heroku.com/" target="_blank">Heroku</a></li>
                <li>Design: <a href="https://startbootstrap.com/theme/creative" target="_blank">Template
                        Bootstrap Creative</a></li>
                <li>Ressources graphiques: <a href="https://unsplash.com" target="_blank">unsplash.com</a> & <a
                        href="https://thenounproject.com" target="_blank">thenounproject.com</a></li>
                <li>Les images en lien avec le film 'Ratatouille' sont la propriété de <a href="https://disney.fr/"
                        target="_blank">Disney</a></li>
            </ul>
        </div>
    </div>

</section>

{% endblock content %}

food_choice/templates/food_choice/products.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Masthead-->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white">{{ title }}</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
            </div>
        </div>
    </div>
</header>

<div class="jumbotron">
    <h2 class="text-center">{{ sentence }}</h2>
</div>

<section>
    <div class="container">
        <div class="row">
            {% for product in products %}
            {% if product.nutrition_grade and product.photo_url %}
            <div class="col-lg-4 col-md-12">

                <a href="{% url 'food_choice:product' product.id %}" title="Fiche produit" target="_blank">
                    <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
                        <img class="card-img-top" src="{{ product.photo_url }}" alt="Image du produit">

                        <span class="nutriscore-{{product.nutrition_grade}}">{{product.nutrition_grade}}</span>

                        <div class="card-body text-center">
                            {% if product.name %}
                            <h6 class="card-title">{{ product.name }}</h6>
                            {% else %}
                            <h6 class="card-title">Nom: non renseigné</h6>
                            {% endif %}

                            <a class="btn btn-primary js-scroll-trigger"
                                href="{% url 'food_choice:substitutes' product.id %}">
                                <img src="{% static 'src/assets/img/substitute.png' %}" alt="Substituer">
                                Substituer</a>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

food_choice/templates/food_choice/research_results.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Masthead-->
{% if research == "substitutes"%}
<header class="masthead"
    style="background: linear-gradient(to bottom, rgba(92, 77, 66, 0.8) 0%, rgba(92, 77, 66, 0.8) 100%), url({{ product_url }}) repeat-x; background-size: contain;">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white">{{ title }}</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
            </div>
        </div>
    </div>
</header>
{% else %}
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white">{{ title }}</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
            </div>
        </div>
    </div>
</header>
{% endif %}

<div class="jumbotron">
    <h2 class="text-center">{{ sentence }}</h2>
</div>

<section>
    <div class="container">
        <div class="row">
            {% for product in products %}
            {% if product.nutrition_grade and product.photo_url %}
            <div class="col-lg-4 col-md-12">

                <a href="{% url 'food_choice:product' product.id %}" title="Fiche produit" target="_blank">
                    <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
                        <img class="card-img-top" src="{{ product.photo_url }}" alt="Image du produit">

                        {% if product.nutrition_grade == "A" %}
                        <span class="nutriscore-A">A</span>
                        {% elif product.nutrition_grade == "B" %}
                        <span class="nutriscore-B">B</span>
                        {% elif product.nutrition_grade == "C" %}
                        <span class="nutriscore-C">C</span>
                        {% elif product.nutrition_grade == "D" %}
                        <span class="nutriscore-D">D</span>
                        {% elif product.nutrition_grade == "E" %}
                        <span class="nutriscore-E">E</span>
                        {% endif %}

                        <div class="card-body text-center">
                            {% if product.name %}
                            <h6 class="card-title">{{ product.name }}</h6>
                            {% else %}
                            <h6 class="card-title">Nom: non renseigné</h6>
                            {% endif %}

                            {% if research == "products" %}
                            <a class="btn btn-primary js-scroll-trigger"
                                href="{% url 'food_choice:substitutes' product.id %}">
                                <img src="{% static 'src/assets/img/substitute.png' %}" alt="Substituer">
                                Substituer</a>
                            {% endif %}

                            {% if user.is_authenticated and research == "substitutes"%}
                            {% if product.id not in favoris %}
                            <a class="btn btn-primary js-scroll-trigger"
                                href="{% url 'food_choice:save_as_favoris' searched_product product.id %}">
                                <img src="{% static 'src/assets/img/save.png' %}" alt="Sauvegarder">
                                Sauvegarder</a>
                            {% else %}
                            <img src="{% static 'src/assets/img/check.png' %}" alt="Favoris">
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

food_choice/templates/food_choice/substitutes.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Masthead-->
<header class="masthead"
    style="background: linear-gradient(to bottom, rgba(92, 77, 66, 0.8) 0%, rgba(92, 77, 66, 0.8) 100%), url({{ product_url }}) repeat-x; background-size: contain;">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white">{{ title }}</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-8 align-self-baseline">
            </div>
        </div>
    </div>
</header>

<div class="jumbotron">
    <h2 class="text-center">{{ sentence }}</h2>
</div>

<section>
    <div class="container">
        <div class="row">
            {% for substitute in substitutes %}
            {% if substitute.nutrition_grade and substitute.photo_url %}
            <div class="col-lg-4 col-md-12">

                <a href="{% url 'food_choice:product' substitute.id %}" title="Fiche produit" target="_blank">
                    <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
                        <img class="card-img-top" src="{{ substitute.photo_url }}" alt="Image du produit">

                        {% if substitute.nutrition_grade == "A" %}
                        <span class="nutriscore-A">A</span>
                        {% elif substitute.nutrition_grade == "B" %}
                        <span class="nutriscore-B">B</span>
                        {% elif substitute.nutrition_grade == "C" %}
                        <span class="nutriscore-C">C</span>
                        {% elif substitute.nutrition_grade == "D" %}
                        <span class="nutriscore-D">D</span>
                        {% elif substitute.nutrition_grade == "E" %}
                        <span class="nutriscore-E">E</span>
                        {% endif %}

                        <div class="card-body text-center">
                            {% if substitute.name %}
                            <h6 class="card-title">{{ substitute.name }}</h6>
                            {% else %}
                            <h6 class="card-title">Nom: non renseigné</h6>
                            {% endif %}

                            {% if user.is_authenticated %}
                            {% if substitute.id not in favoris %}
                            <a class="btn btn-primary js-scroll-trigger"
                                href="{% url 'food_choice:save_as_favoris' searched_product substitute.id %}">
                                <img src="{% static 'src/assets/img/save.png' %}" alt="Sauvegarder">
                                Sauvegarder</a>
                            {% else %}
                            <img src="{% static 'src/assets/img/check.png' %}" alt="Favoris">
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}